#Aplication Configuration
server:
  port: 8092


#To see H2 Console in Browser
#http://localhost:8091/h2-console
#Enabling H2 Console
spring:
  h2:
    console:
      enabled: true

#============================
#JPA
#============================
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update




