spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/molleapaza98/microservices-config-data
          searchPaths: ConfigData
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8090